### PR TITLE
chore: updates Molecula references to FeatureBase

### LINKED ISSUE #2178: Swap Molecula logo to FeatureBase in UI

### PR DESCRIPTION
**Pull request by steppy452**
This PR updates (external) references of Molecula to FeatureBase. Also updated logos and link out to FeatureBase Cloud.

This should also update `yarn.lock` since `package.json` was updated previously but `yarn install` doesn't seem like it was run

Fixes #2178 

image
image
image

### CODE REVIEW

**Review by kcrodgers24 — APPROVED** [review]
Thanks for taking care of this Steph!

**Comment by steppy452** [comment]
@kcrodgers24 the golandci-lint in code checks is failing. am i still good to merge? looks like it's been failing for a little bit and i'm not really touching any go code

**Comment by CLoZengineer** [comment]
@steppy452 you are good.
It had never been turned on before, so it's failing for the existing code, not new code.
Good to ignore it for now, we'll update it to only changed code.

**Comment by steppy452** [comment]
oh.. actually, I think the FeatureBase changes merged over from the other repo? I think we might be good to go without merging this PR

**Comment by kcrodgers24** [comment]
redundant because we synced these changes from the closed repo.

**Pull request closed without merging**
